import { z } from 'zod';

const money = z.number().int().safe();
export const financeAccountSchema = z.object({
  id: z.string(),
  name: z.string(),
  kind: z.enum(['cash', 'bank', 'mono']),
  currency: z.string(),
  balanceMinor: money.nullable(),
  availableMinor: money.nullable().optional(),
  creditLimitMinor: money.nullable().optional(),
  creditLimitSource: z.string().optional(),
  asOf: z.string().nullable(),
  monoId: z.string().nullable(),
  source: z.string(),
});
export const financeTxSchema = z.object({
  id: z.string(),
  at: z.string(),
  amountMinor: money,
  currency: z.string(),
  amountUah: money.nullable(),
  category: z.string(),
  description: z.string(),
  kind: z.string(),
  accountId: z.string().nullable(),
  bank: z.boolean(),
  bankHold: z.boolean().optional(),
  reference: z.string().nullable(),
  personalTaxiType: z.string().nullable().optional(),
});
export const taxiPolicySchema = z.object({
  id: z.string(),
  effectiveAt: z.string(),
  fareBps: z.number().int(),
  commissionBps: z.number().int(),
  fuelBps: z.number().int(),
  tipsBps: z.number().int().min(0).max(10000).default(5000),
  thresholdMinor: money.nullable(),
  bonusFareBps: z.number().int(),
});
export const taxiEntrySchema = z.object({
  id: z.string(),
  at: z.string(),
  policyId: z.string(),
  netCashMinor: money,
  commissionMinor: money,
  fuelMinor: money,
  tipsMinor: money,
  directMinor: money,
  receivedCashMinor: money,
  paidWorkMinor: money,
  commissionReported: z.boolean().default(true),
  cashReported: z.boolean().default(true),
  accountId: z.string().nullable(),
  note: z.string(),
  revision: z.number().int(),
});
export const financeGoalSchema = z.object({
  id: z.string(),
  name: z.string(),
  targetMinor: money,
  deadline: z.string().nullable(),
  status: z.string(),
  planAmountMinor: money.nullable().optional(),
  planPeriod: z.enum(['day', 'week', 'month']).nullable().optional(),
});
export const financeBudgetSchema = z.object({
  id: z.string(),
  category: z.string(),
  categories: z.array(z.string()),
  purpose: z.enum(['expense', 'saving']),
  period: z.enum(['day', 'week', 'month']),
  limitMinor: money.nullable(),
  shareBps: z.number().int().nullable(),
  incomeBaseMinor: money.nullable(),
});
export const financePaymentSchema = z.object({
  id: z.string(),
  name: z.string(),
  kind: z.enum(['subscription', 'loan', 'installment', 'card-installment', 'bill']),
  amountMinor: money,
  remainingMinor: money.nullable(),
  installmentsLeft: z.number().int().nullable(),
  nextDate: z.string(),
  anchorDay: z.number().int(),
  recurrence: z.enum(['day', 'week', 'month', 'year', 'once']),
  category: z.string(),
  remindDays: z.number().int(),
  status: z.string(),
  totalMinor: money.nullable().optional(),
  rateBps: z.number().int().min(0).max(30000).optional(),
  feeMinor: money.optional(),
  lender: z.string().optional(),
  note: z.string().optional(),
  overpaymentTotalMinor: money.nullable().optional(),
  overpaymentRemainingMinor: money.nullable().optional(),
  overpaymentPaidMinor: money.optional(),
  termMonths: z.number().int().nullable().optional(),
  interestMethod: z.enum(['annuity', 'declining', 'flat']).nullable().optional(),
});
export const financeSchema = z.object({
  ok: z.literal(true),
  version: z.number().int(),
  generatedAt: z.string(),
  settings: z.object({
    incomePeriod: z.enum(['week', 'month']),
    taxiVisible: z.boolean(),
    paymentReminders: z.boolean().default(true),
    checkinReminders: z.boolean().default(true),
  }),
  categories: z.array(z.string()),
  accounts: z.array(financeAccountSchema),
  transactions: z.array(financeTxSchema),
  policies: z.array(taxiPolicySchema),
  taxiEntries: z.array(taxiEntrySchema),
  taxiWeeks: z.array(
    z.object({
      key: z.string(),
      grossMinor: money,
      netCashMinor: money.optional(),
      commissionMinor: money.optional(),
      fuelMinor: money.optional(),
      tipsMinor: money.optional(),
      actualSettlementMinor: money.nullable().optional(),
      expectedSettlementMinor: money.optional(),
      settlementDifferenceMinor: money.nullable().optional(),
      settledAt: z.string().nullable().optional(),
      earnedMinor: money,
      heldMinor: money,
      settlementMinor: money,
      complete: z.boolean().default(true),
      settled: z.boolean(),
      closed: z.boolean(),
    }),
  ),
  settlements: z.array(
    z.object({
      id: z.string(),
      weekKey: z.string(),
      expectedMinor: money.nullable().optional(),
      transactionId: z.string().nullable().optional(),
      note: z.string().optional(),
      amountMinor: money,
      accountId: z.string(),
      at: z.string(),
    }),
  ),
  reserveMinor: money,
  goals: z.array(financeGoalSchema),
  goalMoves: z.array(
    z.object({
      id: z.string(),
      goalId: z.string(),
      accountId: z.string(),
      amountMinor: money,
      at: z.string(),
      movementKind: z.enum(['reserve', 'external']).optional(),
      transactionId: z.string().nullable().optional(),
    }),
  ),
  budgets: z.array(financeBudgetSchema),
  payments: z.array(financePaymentSchema),
  detectedSubscriptions: z.array(
    z.object({
      id: z.string(),
      merchant: z.string(),
      amountMinor: money,
      currency: z.string(),
      nextAt: z.string().nullable(),
    }),
  ),
});
export type Finance = z.infer<typeof financeSchema>;
export interface FinanceCommand {
  id: string;
  version: number;
  type: string;
  payload: Record<string, unknown>;
}

export const financeReportSchema = z.object({
  ok: z.literal(true),
  from: z.string(),
  to: z.string(),
  generatedAt: z.string(),
  otherIncomeMinor: money,
  expenseMinor: money,
  taxiEarnedMinor: money,
  settlementDifferenceMinor: money,
  resultMinor: money,
  goalContributionsMinor: money,
  unclassifiedCount: z.number().int(),
  unknownCurrencyCount: z.number().int(),
  bankRetentionDays: z.number().int(),
  categories: z.array(
    z.object({ category: z.string(), amountMinor: money, count: z.number().int() }),
  ),
  daily: z.array(z.object({ date: z.string(), expenseMinor: money, incomeMinor: money })),
  taxiWeeks: z.array(
    z.object({
      key: z.string(),
      grossMinor: money,
      netCashMinor: money,
      commissionMinor: money,
      fuelMinor: money,
      tipsMinor: money,
      earnedMinor: money,
      heldMinor: money,
      expectedMinor: money,
      actualMinor: money.nullable(),
      differenceMinor: money.nullable(),
      complete: z.boolean(),
      closed: z.boolean(),
    }),
  ),
});
export type FinanceReport = z.infer<typeof financeReportSchema>;
